ShowRoom/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin"),
    url(r'^employee/', include('employee.urls')),
    url(r'^parts/',include('parts.urls')),
    url(r'^',include('main.urls')),
    url(r'^vehicle_models/', include('vehicle_models.urls')),
    url(r'^customer/',include('customer.urls')),
    url(r'^workshop/',include('workshop.urls')),
    url(r'^showrooms/',include('showrooms.urls')),

]

customer/urls.py
from django.conf.urls import url
from .views import *
app_name='customer'

urlpatterns=[
    url(r'^customer_list/$',list_customer.as_view(),name='customer_list'),
    url(r'^customer_detail/(?P<pk>\d+)/$',deail_customer.as_view(),name='customer_detail'),
    url(r'^customer_add/$',add_customer.as_view(),name='customer_add'),
    url(r'^customer_update/(?P<pk>\d+)$',update_customer.as_view(),name='customer_update'),
    url(r'^customer_search/',search_customer.as_view(),name='customer_search'),
]

employee/urls.py
from django.conf.urls import url
from . import views

app_name='employee'
urlpatterns = [
    url(r'^$',views.home_page,name='home_page'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name='home'
urlpatterns = [
    url(r'^$',views.home_page,name='home_page'),
]

parts/urls.py
from django.conf.urls import url
from django.urls import reverse

from . import views

app_name='parts'
urlpatterns = [
    url(r'^$',views.part_list_view.as_view(),name='part_list'),
    url(r'^detail/(?P<pk>\d+)/$',views.part_detail_view.as_view(),name='part_detail'),
    url(r'^add$',views.part_add_view.as_view(),name='part_add_view'),
    url(r'^update/(?P<pk>\d+)/$',views.part_update_view.as_view(),name='part_update_view'),
    url(r'^add_stock/$',views.stock_add_view.as_view(),name='stock_add_view'),
    url(r'^update_stock/(?P<pk>\d+)/$',views.stock_update_view.as_view(),name='stock_update_view'),
    url(r'^delete_stock/(?P<pk>\d+)/$',views.stock_delete_view.as_view(),name='stock_delete_view'),
    url(r'^search/',views.part_search_view.as_view(),name='part_search_view'),
    url(r'^add_app/$',views.app_add_view.as_view(),name='app_add_view'),
    url(r'^update_app/(?P<pk>\d+)/$',views.app_update_view.as_view(),name='app_update_view'),
    url(r'^delete_app(?P<pk>\d+)/$',views.app_delete_view.as_view(),name='app_delete_view'),
    url(r'^search_page/$', views.index, name='search_page'),
    url(r'^search_customer/$',views.ajax_customer_search,name='search_customer'),
    url(r'^part_processing/$',views.parts_processing.as_view(), name = 'part_processing'),
    url(r'^part_pro_add/$',views.PartProAdd.as_view(),name= 'part_pro_add')
]

showrooms/urls.py
from django.conf.urls import url
from . import views
from vehicle_models.views import AddManufacturer

app_name='showrooms'

urlpatterns=[


    url(r'^add_model/', AddManufacturer.as_view(), name='add_model'),
    url(r'^newSale/', views.NewSaleView.as_view(), name='newSale'),
    url(r'^salesList/', views.ListSalesView.as_view(), name='salesList'),
    url(r'^$', views.ManufacturerListView.as_view(), name='manufacturerLists'),
    url(r'^manufacturer/category/(?P<pk>\d+)/$', views.CategoryListView.as_view(), name='categoryList'),
    url(r'^manufacturer/category/vehicleName/(?P<pk>\d+)/$', views.VehicleNameListView.as_view(), name='vehicleNameList'),
    url(r'^manufacturer/category/vehicleName/models/(?P<pk>\d+)/$', views.ModelListView.as_view(), name='modelList'),
    url(r'^manufacturer/category/vehicleName/models/details/(?P<pk>\d+)/$', views.ModelDetailsView.as_view(), name='modelDetails'),








]

vehicle_models/urls.py
from .views import *
from django.conf.urls import url

app_name ='vehicle_models'

urlpatterns = [
    url(r'^addImport/',AddModelImport.as_view(),name='addImport'),
    url(r'^processImport/',processImport,name='processImport'),

    url(r'^add_model/',AddManufacturer.as_view(),name='add_model'),
    url(r'^add_category/',AddVehicleCategories.as_view(),name='add_category'),
    url(r'^add_name/',AddVehicleName.as_view(),name='add_name'),
    url(r'^add_new_models/',AddModels.as_view(),name='add_new_models'),
    url(r'^add_model_details/',AddModelDetails.as_view(),name='add_model_details'),
    url(r'^update/(?P<pk>\d+)',UpdateManufacturer.as_view(),name='updateModel'),



]

employee/models.py
from django.db import models

# Create your vehicle_models here.

main/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class department(models.Model):
    name=models.CharField(max_length=30)
    address_city = models.CharField(max_length=30)
    address_district = models.CharField(max_length=30)
    contact = models.BigIntegerField()
    email=models.EmailField()

    def __str__(self):
        return self.name

class employee(models.Model):
    GEND_CHOICES=(
	("Male", ("Male")), 
	("Female", ("Female"))
	)
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    address_city=models.CharField(max_length=30)
    address_district=models.CharField(max_length=30)
    contact=models.BigIntegerField()
    salary=models.IntegerField()
    department_id=models.ForeignKey(department,on_delete=models.CASCADE)
    Gender=models.CharField(max_length=10,choices=GEND_CHOICES)
    joined_date=models.DateField()

    def __str__(self):
        return self.first_name +" "+self.last_name

class user(models.Model):
    user_id=models.OneToOneField(employee,on_delete=models.CASCADE,primary_key=True)
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=30)
    created_date=models.DateField()

    def __str__(self):
        return str(self.username)

    def authenticate(password_entered, username_entered):

        try:
             o=user.objects.get(username=username_entered, password=password_entered)
             return {'status':True, 'department':o.user_id.department_id.name}
        except:
             return False

parts/models.py
from django.db import models
import datetime
from vehicle_models.models import customer_vehicle_info

class part_list(models.Model):
    part_id=models.CharField(max_length=30,unique=True)
    part_name=models.CharField(max_length=30)
    cost=models.IntegerField(default=0)
    available_quantity=models.IntegerField(default=0)

    def __str__(self):
        return self.part_id

class applicable_model(models.Model):
    partId=models.ForeignKey(part_list, on_delete=models.CASCADE)
    applicable=models.CharField(max_length=30)

    def __str__(self):
        return self.partId

class part_stock(models.Model):
    part_id=models.ForeignKey(part_list,on_delete=models.CASCADE)
    entry_date=models.DateField(default=datetime.datetime.today().strftime('%Y-%m-%d'))
    supplier=models.CharField(max_length=30)
    amount=models.IntegerField(default=0)

    def __str__(self):
        return str(self.entry_date)


class part_processing(models.Model):
    pID = models.ForeignKey(part_list,on_delete=models.CASCADE)
    out_date = models.DateField(default=datetime.datetime.today().strftime('%Y-%m-%d'))
    req_form_no = models.IntegerField(default=0)
    quantity = models.IntegerField(default=1)
    vehicle_id = models.ForeignKey(customer_vehicle_info,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.req_form_no)+'-'+str(self.vehicle_id)

workshop/forms.py
from django import forms
from .models import job_records

class jobrecord_form(forms.ModelForm):
    class Meta:
        model = job_records
        fields = '__all__'

employee/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'employee.html')

home/views.py
from django.shortcuts import render

def home_page(request):
    return render(request,'home.html')

parts/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from vehicle_models.models import customer_vehicle_info
from .models import part_list, part_stock, applicable_model,part_processing
from .forms import part_stock_form, applicable_form,part_processing_form
from customer.models import customer_info
from customer.forms import cstm_add_form



def populate_nav_bar():
    gly_name = ['glyphicon glyphicon-plus', 'glyphicon glyphicon-log-out']
    link_list = [ reverse('parts:part_add_view'), reverse('main:logout')]
    link_name = ['Add Part', 'Log Out']
    my_list = zip(gly_name, link_list, link_name)
    return my_list

class part_list_view(ListView):
    model = part_list
    context_object_name = 'part_list'
    template_name = 'part_list.html'

    def get_context_data(self, **kwargs):
        context = super(part_list_view, self).get_context_data(**kwargs)
        context['my_list'] = populate_nav_bar()
        return context

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(part_list_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)

class part_detail_view(DetailView):
    model = part_list
    context_object_name = 'part_detail'
    template_name = 'part_detail.html'

    def get_context_data(self, **kwargs):
        context = super(part_detail_view, self).get_context_data(**kwargs)
        context['my_list'] = populate_nav_bar()
        context['form'] = part_stock_form()
        context['app_add_form'] = applicable_form()
        self.request.session['part_id'] = self.kwargs['pk']
        self.request.session.modified = True
        return context

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(part_detail_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)

class part_add_view(CreateView):
    model = part_list
    fields = ['part_id','part_name','cost']
    template_name = 'part_add.html'
    success_url = reverse_lazy('parts:part_list')

    def get_context_data(self, **kwargs):
        context = super(part_add_view, self).get_context_data(**kwargs)
        context['my_list'] = populate_nav_bar()
        return context

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(part_add_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)

class part_update_view(UpdateView):
    model = part_list
    fields = ['part_id','part_name','cost']
    template_name = 'part_add.html'
    success_url = reverse_lazy('parts:part_list')

    def get_context_data(self, **kwargs):
        context = super(part_update_view, self).get_context_data(**kwargs)
        context['my_list'] = populate_nav_bar()
        return context

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(part_update_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)



class stock_add_view(CreateView):
    model = part_stock
    fields = ['part_id','entry_date','supplier','amount']
    template_name = 'part_detail.html'

    def get_context_data(self, **kwargs):
        context = super(stock_add_view,self).get_context_data(**kwargs)
        context['my_list'] = populate_nav_bar()
        if 'part_id' in self.request.session:
            context['part_detail'] = part_list.objects.get(pk=self.request.session['part_id'])
        return context

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(stock_update_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)

    def get_success_url(self):
        return reverse('parts:part_detail',args=[self.request.session['part_id']])

    def post(self, request, *args, **kwargs):
        form = part_stock_form(request.POST)
        if form.is_valid():
            part_id = form.cleaned_data['part_id']
            amount = form.cleaned_data['amount']
            temp = part_list.objects.get(part_id = part_id)
            temp.available_quantity+=amount
            temp.save()

        return super(stock_add_view,self).post(request,*args, **kwargs)

class stock_update_view(UpdateView):
    model = part_stock
    fields = ['part_id','entry_date','supplier','amount']
    template_name = 'part_stock_form.html'

    def get_context_data(self, **kwargs):
        context = super(stock_update_view, self).get_context_data(**kwargs)
        context['my_list'] = populate_nav_bar()
        context['update_form'] = context.get('form')
        return context

    def form_invalid(self, form):
        return render(self.request, 'part_detail.html', {'form':part_stock_form(),'update_form': form,'app_add_form':applicable_form(), 'part_detail': part_list.objects.get(pk=self.request.session['part_id'])})

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(stock_update_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)

    def get_success_url(self):
        return reverse('parts:part_detail', args=[self.request.session['part_id']])

    def post(self, request, *args, **kwargs):
        form = part_stock_form(request.POST)
        if form.is_valid():
            part_id = form.cleaned_data['part_id']
            amount = form.cleaned_data['amount']
            temp = part_list.objects.get(part_id = part_id)
            temp2 =part_stock.objects.get(pk = self.kwargs['pk'])
            prevAmount = temp2.amount
            temp.available_quantity+=amount-prevAmount
            temp.save()

        return super(stock_update_view,self).post(request,*args, **kwargs)


class stock_delete_view(DeleteView):
    model = part_stock
    success_url = reverse_lazy('parts:part_list')
    template_name = 'part_stock_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super(stock_delete_view, self).get_context_data(**kwargs)
        context['delete_form'] = context.get('form')
        return context

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == False:
            if temp == True:
                return super(stock_delete_view, self).get(request, *args, **kwargs)
            else:
                return HttpResponseRedirect(temp)

    def post(self, request, *args, **kwargs):
        temp =part_stock.objects.get(pk = self.kwargs['pk'])
        temp2 = part_list.objects.get(part_id=temp.part_id)
        temp2.available_quantity-=temp.amount
        temp2.save()
        return super(stock_delete_view,self).post(request,*args, **kwargs)

class part_search_view(ListView):
    model = part_list
    context_object_name = 'part_list'
    template_name = 'part_list.html'

    def get_context_data(self, **kwargs):
        context = super(part_search_view, self).get_context_data(**kwargs)
        context['my_list'] = populate_nav_bar()
        return context

    def get_queryset(self):
        key = self.request.GET['search_text']
        partlist = part_list.objects.filter(Q(part_id__icontains=key) | Q(part_name__icontains=key))
        return partlist

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(part_search_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)


class app_add_view(CreateView):
    model = applicable_model
    fields = ['partId', 'applicable']
    success_url = reverse_lazy('parts:part_list')
    template_name = 'part_detail.html'

    def get_context_data(self, **kwargs):
        context = super(app_add_view, self).get_context_data(**kwargs)
        if 'part_id' in self.request.session:
            context['part_detail'] = part_list.objects.get(pk=self.request.session['part_id'])
        return context

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(app_add_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)

class app_update_view(UpdateView):
    model = applicable_model
    fields = ['partId', 'applicable']
    success_url = reverse_lazy('parts:part_list')
    template_name = 'app_update_form.html'

    def get_context_data(self, **kwargs):
        context = super(app_update_view, self).get_context_data(**kwargs)
        context['app_update_form'] = context.get('form')
        return context

    def form_invalid(self, form):
        return render(self.request, 'part_detail.html', {'app_add_form':applicable_form(),'app_update_form': form, 'part_detail':  part_list.objects.get(pk=self.request.session['part_id'])})

    def get(self, request, *args, **kwargs):
        temp = check_session_exist(self.request)
        if temp == True :
            return super(app_update_view, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(temp)

class app_delete_view(DeleteView):
    model = applicable_model
    success_url = reverse_lazy('parts:part_list')
    template_name = 'app_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super(app_delete_view, self).get_context_data(**kwargs)
        if 'part_id' in self.request.session:

templates/add_model.html
{% extends 'model_base.html' %}
{% block body %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="row">


        <div class="col-sm-4">
          <div class="panel panel-primary">

              <div class="panel-heading">
                    <h3 class="panel-title">Manufacturer</h3>
              </div>

              <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ Manufacturer.as_p }}
                    <button type="submit">Add</button>
                </form>
              </div>
          </div>
        </div>



     <div class="col-sm-4">
          <div class="panel panel-primary">

              <div class="panel-heading">
                    <h3 class="panel-title">Vehicle Category</h3>
              </div>

              <div class="panel-body">
                <form action="{% url 'vehicle_models:add_category' %}" method="post">
                    {% csrf_token %}
                    {{ Category.as_p }}
                    <button type="submit">Add</button>
                </form>
              </div>
          </div>
        </div>




    <div class="col-sm-4">
          <div class="panel panel-primary">

              <div class="panel-heading">
                    <h3 class="panel-title">Vehicle Name</h3>
              </div>

              <div class="panel-body">
                <form action="{% url 'vehicle_models:add_name'%}" method="post">
                    {% csrf_token %}
                    {{ VehicleName.as_p }}
                     <button type="submit">Add</button>
                    </form>
                </form>
              </div>
          </div>
        </div>



    <div class="col-sm-4">
          <div class="panel panel-primary">

              <div class="panel-heading">
                    <h3 class="panel-title">Vehicle Models</h3>
              </div>

              <div class="panel-body">
                <form action="{% url 'vehicle_models:add_new_models'%}" method="post">
                    {% csrf_token %}
                    {{ Model.as_p }}
                     <button type="submit">Add</button>
                </form>
              </div>
          </div>
        </div>



    <div class="col-sm-4">
          <div class="panel panel-primary">

              <div class="panel-heading">
                    <h3 class="panel-title">Model Details</h3>
              </div>

              <div class="panel-body">
                <form action="{% url 'vehicle_models:add_model_details'%}" method="post">
                    {% csrf_token %}
                    {{ ModelDetails.as_p }}
                    <button type="submit">Add</button>
                </form>
              </div>
          </div>
        </div>




    <div class="col-sm-4">
          <div class="panel panel-primary">

              <div class="panel-heading">
                    <h3 class="panel-title">Model Imports</h3>
              </div>

              <div class="panel-body">
                <form action="{% url 'vehicle_models:addImport'%}" method="post">
                    {% csrf_token %}
                    {{ ImportDetails.as_p }}
                    <button type="submit">Add</button>
                </form>
              </div>
          </div>
        </div>




</div>

{% endblock %}


<span> ..............................Manufacturer.............................</span>
<form action="" method="post">
    {% csrf_token %}
    {{ Manufacturer.as_p }}
    <button type="submit">Add</button>
</form>



<span> ............................Vehicle Category..............................</span>

<form action="{% url 'vehicle_models:add_category' %}" method="post">
    {% csrf_token %}
    {{ Category.as_p }}
    <button type="submit">Add</button>
</form><br><br>




<span> .................Vehicle Name.............................................</span>


<form action="{% url 'vehicle_models:add_name'%}" method="post">
    {% csrf_token %}
    {{ VehicleName.as_p }}
    <button type="submit">Add</button>
</form><br><br>

<span> ..............................Models...................................</span>


<form action="{% url 'vehicle_models:add_new_models'%}" method="post">
    {% csrf_token %}
    {{ Model.as_p }}
    <button type="submit">Add</button>
</form><br><br>


<span> .................................Model Details............................</span>

<form action="{% url 'vehicle_models:add_model_details'%}" method="post">
    {% csrf_token %}
    {{ ModelDetails.as_p }}
    <button type="submit">Add</button>
</form><br><br>


<span> .................................Model Import............................</span>

<form action="{% url 'vehicle_models:addImport'%}" method="post">
    {% csrf_token %}
    {{ ImportDetails.as_p }}
    <button type="submit">Add</button>
</form><br><br>


<span> .................................Model Import(Beta)............................</span>

<form action="{% url 'vehicle_models:processImport'%}" method="post">
    {% csrf_token %}
    {{ ImportDetails.as_p }}
    <button type="submit">Add</button>
</form><br><br>

templates/employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'nav_bar_base.html' %}
</html>

templates/employee_add.html
 {% extends 'employee_base.html' %}

 {% block body %}
     <form method="post">
         {% csrf_token %}
           {{ form.as_p }}
            <input type="submit" value="Save" />
     </form>
 {% endblock %}

templates/employee_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>customer</title>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock %}
</head>
<body>
{% block nav-bar %}
    <div>
        {% include 'nav_bar_base.html' with my_list=my_list search_link='main:employee_search' home_link='main:employee_list' %}
    </div>
    <br><br><br><br>
{% endblock %}

{% block body %}

{% endblock %}

</body>
</html>

templates/hr.html
<html>
<head>
<title> HR Department </title>
<head>
<body>
	<center><h1> HR Department </h1></center>
	<hr>
	<br>
{% include hr_search.html %}




</body>
</html>

templates/model_add.html
{% extends 'model_base.html' %}
{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

templates/model_list.html
{% extends 'model_base.html' %}

{% block body %}

{% for model in model_list %}
<a href="{% url 'showrooms:modelDetails' model.id %}" class="list-group-item">{{ model.model }}</a><br>




{% endfor %}

{% endblock %}

templates/part_app_model.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(function(){
        $('.edit').on('click',display_popup);
        
            function display_popup() {
                $("#pop_up").show();
                $("#id_edit_app-app_id").val($(this).data("id")).hide();
                $("#id_edit_app-applicable").val($(this).data("app_name"));
            }

        });
    </script>
</head>
<body>
<div style="position: fixed;">
    {% include 'nav_bar_base.html' with my_list=my_list search_link='parts:part_search_view' %}
</div>
<br><br><br><br>
{% block add_app_model %}
    <div style="position: relative;">
    <form id="add_app_form" method="post" action="{% url 'parts:part_app_model' part_temp.part_id %}">
        {% csrf_token %}
        {{ add_app.applicable }}
        <input type="submit" name="add_app_btn">
    </form>
    </div>
{% endblock %}

{% block list_app %}
    {% for app_model in part_temp.applicable_model_set.all %}
        {{ app_model }}
        <button type="button" data-id="{{ app_model.id }}" data-app_name="{{ app_model.applicable }}" class="edit">Edit</button>
        <br>
    {% endfor %}
{% endblock %}

{% block edit_form %}
    <div id="pop_up" style="display: none;">
    <form method="post"  action="">
        {% csrf_token %}
        {{ edit_app.app_id }}
        {{ edit_app.applicable }}
        <input type="submit"name="edit_app_btn">
    </form>
    </div>
{% endblock %}
</body>
</html>

templates/part_list.html
{% extends 'parts_base.html' %}

{% block body %}
    <div class="container">
    <h2 align="center">Part List</h2>
<ul class="list-group">
{% for part in part_list %}
     <a href="{% url 'parts:part_detail' part.id %}" class="list-group-item">{{ part.part_id }} - {{ part.part_name }}</a>
{% endfor %}
</ul>
    </div>
{% endblock %}

templates/parts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parts</title>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<div>
{% include 'nav_bar_base.html' with my_list=my_list search_link='parts:part_search_view' %}
</div>
<br><br><br>

<div class="container"  >
  <h2>List Group With Linked Items</h2>
  <div class="list-group">
    {% for part in part_list %}
        <a href="{% url 'parts:part_details' part.part_id %}" class="list-group-item">{{ part.part_id }} - {{ part.part_name }}</a>
    {% endfor %}
  </div>
</div>


</body>
</html>

templates/parts_processing.html
{% extends 'parts_base.html' %}

{% block javascript %}
    <script type="text/javascript">
        $(function () {


        })
    </script>
{% endblock %}

{% block body %}
    <div class="container">
    <a href="{% url 'customer:customer_add' %}">Add New customer</a>
    <h3>
    Part ID:{{ part_detail.part_id }}<br>
    Name:{{ part_detail.part_name }}<br>
    Cost:{{ part_detail.cost }}<br>
    Remaining Quantity:{{ part_detail.available_quantity }}</h3>
    <hr>
    {% include 'index.html' %}



    <div>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Out Date</th>
            <th>Form No</th>
            <th>Customer</th>
        </tr>
        </thead>
        <tbody>
        {% for result in part_detail.part_processing_set.all %}
            <tr>
            <td>{{ result.pID }}</td>
            <td>{{ result.out_date }}</td>
            <td>{{ result.req_form_no }}</td>
            <td>{{ result.vehicle_id.customerId }}</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

    </div>
    </div>
{% endblock %}